- hosts: localhost
  connection: local
  vars:
    instanceid: 'd90612e9-ee23-44f4-b49c-112202b608fc'
    admin_pass: 'Vmware123!'
    public_ip: "144.130.51.227"
  tasks:
   - vca_vapp:
       state: present
       operation: poweron
       instance_id: "{{ instanceid }}"
       vdc_name: 'mreferre'
       catalog_name: "Public Catalog"
       template_name: "CentOS64-64BIT"
       vm_name: VMdemo
       network_mode: pool
       admin_password: '{{ admin_pass }}'
       network_name: "default-routed-network"

     register: myvm

   - debug: var=myvm

   - vca_nat:
       instance_id: "{{ instanceid }}"
       vdc_name: 'mreferre'
       state: present
       nat_rules:
         - rule_type: DNAT
           original_ip: "{{ public_ip }}"
           translated_ip: "{{ myvm.vm_details.network_info.ip }}"
   - vca_fw:
       instance_id: '{{ instanceid }}'
       vdc_name: 'mreferre'
       state: present
       fw_rules:
         - description: "Allow all trafic to the public ip"
           source_ip: "Any"
           dest_ip: "{{ public_ip }}"


#   - wait_for: host="{{ public_ip }}" state=started delay=5

   - add_host: name="{{ public_ip }}" groups=nginx ansible_ssh_password="{{ admin_pass }}"


- hosts: nginx
  roles: 
    - role: nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        default:
          - listen 80
          - location / { try_files $uri $uri/ /index.html; }
          - location /images/ { try_files $uri $uri/ /index.html; }
